version: "3.7"
services:
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    working_dir: /postgres
    volumes:
          - ./:/postgres
    environment:
      POSTGRES_DB: selectel
      POSTGRES_USER: selectel
      POSTGRES_PASSWORD: selectel
