version: "3"

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: selectel
      POSTGRES_PASSWORD: selectel
